### ISSUE TITLE
Get pancake working in Windows

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/pancake#14]
Windows is the new IE for node devs.
Areas that need attention from looking at initial tests:

- [x] The bash script in each module won't work naturally
- [x] Spawning new processes don't go down as they should. Need to look at that
- [x] The Sass paths need to be adapted to each os
- [x] Get folder creating to work

**Comment by elisechant** [comment]
try cross-env npm plugin

**Comment by dominikwilkowski** [comment]
That's all good. Thanks @elisechant 

The only two problems I ad was getting rid of the bash script which is done already and spawning a child process which is easily done with:

```js
const npmVersion = parseInt(Spawn('cmd.exe', ['/s','/c','npm', '-v']).stdout);
```

Sniffing OS is done with:

```js
var isWin = /^win/.test(process.platform);
```
_(can't use `os.platform()` as we support node 5)_
