### ISSUE TITLE
Investigate the speed in which plugins are installed

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/pancake#20]
Right now running:
```shell
npm i @gov.au/pancake-js @gov.au/pancake-sass @gov.au/testmodule3
```
is faster than
```shell
npm i @gov.au/testmodule3
```

**Comment by dominikwilkowski** [comment]
Related to nodejs/node#3429 it seems.

Investigate the speed between `child_process.exec` and `child_process.spawn`.
Read: https://medium.com/@graeme_boy/how-to-optimize-cpu-intensive-work-in-node-js-cdc09099ed41

**Comment by simonschwartz** [comment]
NodeJS docs on child_process and cluster https://nodejs.org/api/child_process.html
