### ISSUE TITLE
Make required a setting inside the package.json pancake object

### ISSUE THREAD

**Issue by alex-page** [govau/pancake#52]
As a user I don't want pancake to create a certain type of file as my project doesn't use it (sass/css/react/js). 

Currently users have odd ways of doing this such as setting the `"name"` value in `package.json` to `false`. This works ok but it's not clear to the user that setting `"name"` to `false` stops the generation of files. It also doesn't work with the react plugin as that creates unique names per component.

There should be a new value (required) in the `package.json` pancake object which allows users to choose which types of files they want processed.

This may lead to a further conversation about component dependencies. It would be nice to `npm install @gov.au/select` and be able to choose if I would like to install `pancake-sass`, `pancake-react` which would then create the files.

**Comment by dominikwilkowski** [comment]
Is the `ignore` key enough for this?

You can set it in your `package.json` file https://github.com/govau/pancake#local-settings or as a cli flag https://github.com/govau/pancake#overwrite-the-plugin-ignore-list

**Comment by alex-page** [comment]
Sounds good to me.
