### ISSUE TITLE
Pancake monorepo suppport, allow users to set node_modules directory location

### ISSUE THREAD

**Issue by AlexGilleran** [govau/pancake#59]
We're using pancake with the govau design systems modules over at https://github.com/terriajs/magda.

Magda is a lerna monorepo, with node_modules at the root and in each subdirectory.

I've been trying to switch over to using yarn instead of npm. Yarn puts most dependencies in the root node_modules directory, but our react web app lives in `magda-web-client` subdirectory. So when I run `pancake` from that directory, it says `🔔  INFO:    No modules found` because it can't find any modules in `magda-web-client/node_modules`, and doesn't know to recurse upwards.

Looking at the code, it looks like the directory where modules are found has to be process.cwd + 'node_modules' - could that be configurable, or know to keep recursing upwards adding modules until it can't find any more node_modules directories?

**Comment by maxious** [comment]
This assumption applies to both the pancake plugins https://github.com/govau/pancake/blob/master/packages/pancake/src/plugins.js#L53 and the actual pancake module content https://github.com/govau/pancake/blob/master/packages/pancake/src/modules.js#L90

**Comment by alex-page** [comment]
What a nice way to enhance developer experience your users of yarn! Definitely haven't thought about this before. 

In the [uikit](https://github.com/govau/uikit) project you can see how we address lerna and pancake per package:
- https://github.com/govau/uikit/blob/master/packages/accordion/package.json
- https://github.com/govau/uikit/blob/master/package.json

This works for us but definitely could be enhanced by moving the design system components to the parent `node_modules` and running pancake pointing at the parent `node_modules`.
