### ISSUE TITLE
Selecting minified JS option causes bugs on ie8

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/pancake#73]
# What happened

When the JS is minified option is selected as true, the side-nav doesn't open or close in ie8 on smaller devices

```JS
"js": {
		"minified": true,
		"modules": false,
		"location": "docs/js/",
		"name": "script.js"
	},
```

# What I expected to happen

I expected the side-nav to open and close when I click it

# Reproducing

- Pancake version: v1.2.3

Steps to reproduce:

1. As an example, run [uikit-starter](https://github.com/govau/uikit-starter) project on ie8 and try to open/close the accordion

2. Then try setting the `minified` option to `false`

**Comment by alex-page** [comment]
Should be this line of code:
https://github.com/govau/pancake/blob/master/packages/pancake-js/src/js.js#L40
