### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/pancake#8]
Write tests for each section:

**batter**
- [ ] with conflicts
- [ ] without conflicts
- [ ] no modules
- [ ] no node_modules

**syrup**
- [ ] sass only
- [ ] sass and js
- [ ] no assets at all
- [ ] no folder
- [ ] not writable folder
- [ ] all settings individually

**cream**
- [ ] mock uikit.json
- [ ] on empty folder
- [ ] on patch changes
- [ ] on minor changes
- [ ] on major changes
- [ ] on modules that don't exist anymore

**Comment by klepas** [comment]
Can I help with this in any way?

**Comment by dominikwilkowski** [comment]
Always :)
I can run you through this tomorrow but for now I need to create a working set of testing modules to test with.
https://www.npmjs.com/org/gov.au

We go from there.
