### ISSUE TITLE
Pancake modules from multiple organisations

### ISSUE THREAD

**Issue by alex-page** [govau/pancake#85]
We need to investigate if this is possible or how much work it would require to support this feature.

**Comment by maxious** [comment]
I think it is possible if you are very careful not to include two cores or anything like that. 

The default setting npmOrgs should be made a list https://github.com/govau/pancake/blob/21d154d17aef148c74ad0d7072c02a898cf75a4b/packages/pancake/settings.json

Then you could search multiple folders to compile all the pancake candidate npm packages https://github.com/govau/pancake/blob/74492f55be2d68ce3b013ea7a497c833efca0680/packages/pancake/src/modules.js#L85
